services:
  frontend:
    image: nginx-frontend
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      # folder with the generated tmaps
      - /mnt/10tb_hdd/clustered_enamine_database/tmaps:/usr/share/nginx/html/generated_tmaps
    networks:
      - chelombus-network

  clickhouse:
    image: clickhouse:latest
    environment:
      - HOME=/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /mnt/10tb_hdd/uncleaned_data:/var/lib/clickhouse/user_files/uncleaned_data
      - /mnt/10tb_hdd/config/:/etc/clickhouse-server/config.d
      - /mnt/samsung_2tb/mixed_data:/var/lib/clickhouse/user_files/mixed_data
      - /mnt/10tb_hdd/main_data:/var/lib/clickhouse
      - ./shared_volume:/shared_volume
    networks:
      - chelombus-network

  dynamic-tmap:
    user: root
    build: ./dynamic_tmap
    volumes:
      - ./shared_volume:/app/generated_tmaps
      - /mnt/10tb_hdd/:/data
      - /mnt/samsung_2tb/mixed_data:/data/parquet_files
      - /home/afloresep/miniforge3/envs/chelombus:/opt/conda/envs/chelombus
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    depends_on:
      - clickhouse
    networks:
      - chelombus-network

  pyspark:
    image: pyspark
    build: ./pyspark
    volumes:
      - /mnt/10tb_hdd/:/data/parquet_files
      - /mnt/samsung_2tb/mixed_data:/data/parquet_files
      - ./shared_volume:/shared_volume
      - ./pyspark/scripts:/app/scripts
    depends_on:
      - dynamic-tmap
      - clickhouse
    networks:
      - chelombus-network

volumes:
  clickhouse_data:

networks:
  chelombus-network:
