services:
  frontend:
    image: nginx-frontend
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./shared_volume:/usr/share/nginx/html/generated_tmaps
    depends_on:
      - dynamic-tmap 
    networks:
      - chelombus-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /mnt/10tb_hdd/:/var/lib/clickhouse/user_files/data
      - ./shared_volume:/shared_volume
    networks:
      - chelombus-network

  dynamic-tmap:
    build: ./dynamic_tmap
    volumes:
      - ./shared_volume:/app/generated_tmaps
      - /mnt/10tb_hdd/:/data
      - /home/afloresep/miniforge3/envs/chelombus:/opt/conda/envs/chelombus
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    depends_on:
      - clickhouse
    networks:
      - chelombus-network

  pyspark:
    image: pyspark
    build: ./pyspark
    volumes:
      - /mnt/10tb_hdd/:/data/parquet_files
      - ./shared_volume:/shared_volume
      - ./pyspark/scripts:/app/scripts
    depends_on:
      - dynamic-tmap
      - clickhouse
    networks:
      - chelombus-network

volumes:
  clickhouse_data:

networks:
  chelombus-network:
